[project]
name = "reverse-proxy-flask"
version = "0.0.1"
description = "Reverse Proxy implemented with Flask"
readme = "README.md"
requires-python = "==3.14.0"
dependencies = [
    "black==25.11.0",
    "flask==3.1.2",
    "requests==2.32.5",
    "ruff==0.14.5",
]
