[project]
name = "revers-proxy-fastapi"
version = "0.0.1"
description = "Reverse Proxy implemented with FastAPI"
readme = "README.md"
requires-python = "==3.14.0"
dependencies = [
    "black==25.9.0",
    "fastapi==0.121.0",
    "httpx==0.28.1",
    "ruff==0.14.4",
    "uvicorn==0.38.0",
]
